### ISSUE TITLE
Unable to create an account in the local environment

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/liberapay.com#1228]
I have the following errror when trying to create an account in the local environmnet. After filling my email, I have the following error:

```
500
Erreur interne

On dirait que vous avez trouvé un bogue ! Désolé pour ce désagrément, nous allons le corriger le plus vite possible !
```

I supposed it was related to  #106 but apparently it is definitly fixed.

I must precise that I use the same browser than the one I'm connected on the https://liberapay.com/ plateform. If I use another browser, creating a account works fine.

**Comment by MartinDelille** [comment]
Here is the log:

```

web_1  | [02/Sep/2018:07:57:35 +0000] 200 0.158501s localhost:8339 "GET /sign-in?back_to=/ HTTP/1.1" 14963 "http://localhost:8339/"
web_1  | [02/Sep/2018:07:57:35 +0000] 200 0.146871s localhost:8339 "GET /assets/base.css HTTP/1.1" 45436 "http://localhost:8339/sign-in?back_to=/"
web_1  | [02/Sep/2018:07:57:35 +0000] 200 0.020763s localhost:8339 "GET /assets/forkawesome/1.0.11/css/fork-awesome.min.css HTTP/1.1" 32249 "http://localhost:8339/sign-in?back_to=/"
web_1  | [02/Sep/2018:07:57:35 +0000] 200 0.012598s localhost:8339 "GET /assets/jquery.min.js HTTP/1.1" 85578 "http://localhost:8339/sign-in?back_to=/"
web_1  | [02/Sep/2018:07:57:35 +0000] 200 0.019662s localhost:8339 "GET /assets/bootstrap/js/bootstrap.min.js HTTP/1.1" 37045 "http://localhost:8339/sign-in?back_to=/"
web_1  | [02/Sep/2018:07:57:35 +0000] 200 0.068245s localhost:8339 "GET /assets/base.js HTTP/1.1" 89161 "http://localhost:8339/sign-in?back_to=/"
web_1  | [02/Sep/2018:07:57:36 +0000] 200 0.515119s localhost:8339 "GET /assets/bootstrap/css/bootstrap.css HTTP/1.1" 151091 "http://localhost:8339/sign-in?back_to=/"
web_1  | [02/Sep/2018:07:57:36 +0000] 200 0.020792s localhost:8339 "GET /assets/bootstrap/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 18028 "http://localhost:8339/assets/bootstrap/css/bootstrap.css"
web_1  | [02/Sep/2018:07:57:36 +0000] 200 0.025998s localhost:8339 "GET /assets/forkawesome/1.0.11/fonts/forkawesome-webfont.woff2?v=1.0.11 HTTP/1.1" 85264 "http://localhost:8339/assets/forkawesome/1.0.11/css/fork-awesome.min.css"
web_1  | [02/Sep/2018:07:57:36 +0000] 200 0.019241s localhost:8339 "GET /assets/fonts/ubuntu-regular-webfont.woff2 HTTP/1.1" 100100 "http://localhost:8339/assets/base.css"
web_1  | [02/Sep/2018:07:58:03 +0000] 200 0.161432s localhost:8339 "GET /sign-up HTTP/1.1" 15140 "http://localhost:8339/sign-in?back_to=/"
web_1  | [02/Sep/2018:07:58:03 +0000] 200 0.121513s localhost:8339 "GET /assets/base.css HTTP/1.1" 45436 "http://localhost:8339/sign-up"
web_1  | [02/Sep/2018:07:58:03 +0000] 200 0.023134s localhost:8339 "GET /assets/forkawesome/1.0.11/css/fork-awesome.min.css HTTP/1.1" 32249 "http://localhost:8339/sign-up"
web_1  | [02/Sep/2018:07:58:03 +0000] 200 0.016698s localhost:8339 "GET /assets/bootstrap/js/bootstrap.min.js HTTP/1.1" 37045 "http://localhost:8339/sign-up"
web_1  | [02/Sep/2018:07:58:03 +0000] 200 0.012010s localhost:8339 "GET /assets/jquery.min.js HTTP/1.1" 85578 "http://localhost:8339/sign-up"
web_1  | [02/Sep/2018:07:58:03 +0000] 200 0.059350s localhost:8339 "GET /assets/base.js HTTP/1.1" 89161 "http://localhost:8339/sign-up"
web_1  | [02/Sep/2018:07:58:03 +0000] 200 0.527806s localhost:8339 "GET /assets/bootstrap/css/bootstrap.css HTTP/1.1" 151091 "http://localhost:8339/sign-up"
web_1  | [02/Sep/2018:07:58:03 +0000] 200 0.018660s localhost:8339 "GET /assets/fonts/ubuntu-regular-webfont.woff2 HTTP/1.1" 100100 "http://localhost:8339/assets/base.css"
web_1  | [02/Sep/2018:07:58:03 +0000] 200 0.015631s localhost:8339 "GET /assets/fonts/ubuntu-medium-webfont.woff2 HTTP/1.1" 90748 "http://localhost:8339/assets/base.css"
web_1  | [02/Sep/2018:07:58:03 +0000] 200 0.016389s localhost:8339 "GET /assets/bootstrap/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 18028 "http://localhost:8339/assets/bootstrap/css/bootstrap.css"
web_1  | [02/Sep/2018:07:58:03 +0000] 200 0.021342s localhost:8339 "GET /assets/forkawesome/1.0.11/fonts/forkawesome-webfont.woff2?v=1.0.11 HTTP/1.1" 85264 "http://localhost:8339/assets/forkawesome/1.0.11/css/fork-awesome.min.css"
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python2.7/dist-packages/algorithm.py", line 321, in loop
web_1  |     new_state = function(**deps.as_kwargs)
web_1  |   File "/app/liberapay/security/authentication.py", line 174, in authenticate_user_if_possible
web_1  |     p = sign_in_with_form_data(body, state)
web_1  |   File "/app/liberapay/security/authentication.py", line 133, in sign_in_with_form_data
web_1  |     p.add_email(email, cursor=c)
web_1  |   File "/app/liberapay/models/participant.py", line 914, in add_email
web_1  |     r = self.send_email('verification', email, link=link.format(**locals()), old_email=old_email)
web_1  |   File "/app/liberapay/models/participant.py", line 1051, in send_email
web_1  |     website.log_email(message)
web_1  |   File "/app/liberapay/wireup.py", line 343, in log_email
web_1  |     print(html)
web_1  | UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 126: ordinal not in range(128)
web_1  | [02/Sep/2018:07:58:12 +0000] 500 0.192907s localhost:8339 "POST /sign-up HTTP/1.1" 7774 "http://localhost:8339/sign-up"
web_1  | [02/Sep/2018:07:58:12 +0000] 200 0.121579s localhost:8339 "GET /assets/base.css HTTP/1.1" 45436 "http://localhost:8339/sign-up"
web_1  | [02/Sep/2018:07:58:12 +0000] 200 0.009640s localhost:8339 "GET /assets/jquery.min.js HTTP/1.1" 85578 "http://localhost:8339/sign-up"
web_1  | [02/Sep/2018:07:58:12 +0000] 200 0.018936s localhost:8339 "GET /assets/forkawesome/1.0.11/css/fork-awesome.min.css HTTP/1.1" 32249 "http://localhost:8339/sign-up"
web_1  | [02/Sep/2018:07:58:12 +0000] 200 0.013681s localhost:8339 "GET /assets/bootstrap/js/bootstrap.min.js HTTP/1.1" 37045 "http://localhost:8339/sign-up"
web_1  | [02/Sep/2018:07:58:12 +0000] 200 0.062341s localhost:8339 "GET /assets/base.js HTTP/1.1" 89161 "http://localhost:8339/sign-up"
web_1  | [02/Sep/2018:07:58:13 +0000] 200 0.452722s localhost:8339 "GET /assets/bootstrap/css/bootstrap.css HTTP/1.1" 151091 "http://localhost:8339/sign-up"
web_1  | [02/Sep/2018:07:58:13 +0000] 200 0.018344s localhost:8339 "GET /assets/fonts/ubuntu-regular-webfont.woff2 HTTP/1.1" 100100 "http://localhost:8339/assets/base.css"
web_1  | [02/Sep/2018:07:58:13 +0000] 200 0.024843s localhost:8339 "GET /assets/forkawesome/1.0.11/fonts/forkawesome-webfont.woff2?v=1.0.11 HTTP/1.1" 85264 "http://localhost:8339/assets/forkawesome/1.0.11/css/fork-awesome.min.css"
web_1  | [02/Sep/2018:07:58:13 +0000] 200 0.016287s localhost:8339 "GET /assets/fonts/ubuntu-medium-webfont.woff2 HTTP/1.1" 90748 "http://localhost:8339/assets/base.css"
web_1  | [02/Sep/2018:07:58:13 +0000] 200 0.015053s localhost:8339 "GET /assets/bootstrap/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 18028 "http://localhost:8339/assets/bootstrap/css/bootstrap.css"
```

**Comment by MartinDelille** [comment]
And the request header:

```
POST /sign-up HTTP/1.1
Host: localhost:8339
Connection: keep-alive
Content-Length: 154
Cache-Control: max-age=0
Origin: http://localhost:8339
Upgrade-Insecure-Requests: 1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Referer: http://localhost:8339/sign-up
Accept-Encoding: gzip, deflate, br
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,es;q=0.6
Cookie: wordpress_test_cookie=WP+Cookie+check; _ga=GA1.1.1282274108.1532330956; wp-settings-time-1=1532331241; csrf_token=3rPZIoyuwoomu2fQkD7YlOTqxoU0SEyY
```

and the response header:

```
HTTP/1.1 500 Internal Server Error
Server: gunicorn/19.6.0
Date: Sun, 02 Sep 2018 08:00:13 GMT
Connection: close
Transfer-Encoding: chunked
Set-Cookie: csrf_token=3rPZIoyuwoomu2fQkD7YlOTqxoU0SEyY; expires=Sun, 09 Sep 2018 08:00:13 GMT; Path=/; SameSite=lax
Content-Type: text/html; charset=UTF-8
Cache-Control: no-cache
```

**Comment by mattbk** [comment]
> web_1  | UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 126: ordinal not in range(128)

Looks like é is a bad character.

**Comment by MartinDelille** [comment]
The thing is there is no é in my email. Where can this come from?

**Comment by MartinDelille** [comment]
Not reproduced.
