### ISSUE TITLE
Error when deploying the site locally

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/liberapay.com#1237]
I just updated my local repository and I have a problem when starting the site locally:

```
$ docker-compose up
Starting liberapaycom_db_1 ... done
Starting liberapaycom_web_1 ... done
Attaching to liberapaycom_db_1, liberapaycom_web_1
db_1   | LOG:  database system was shut down at 2018-09-04 08:21:03 UTC
db_1   | LOG:  MultiXact member wraparound protections are now enabled
db_1   | LOG:  database system is ready to accept connections
db_1   | LOG:  autovacuum launcher started
web_1  | [2018-09-13 13:24:03 +0000] [9] [INFO] Starting gunicorn 19.6.0
web_1  | [2018-09-13 13:24:03 +0000] [9] [INFO] Listening at: http://0.0.0.0:8339 (9)
web_1  | [2018-09-13 13:24:03 +0000] [9] [INFO] Using worker: sync
web_1  | [2018-09-13 13:24:03 +0000] [13] [INFO] Booting worker with pid: 13
web_1  | [2018-09-13 13:24:03 +0000] [15] [INFO] Booting worker with pid: 15
web_1  | [2018-09-13 13:24:05 +0000] [15] [ERROR] Exception in worker process
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
web_1  |     worker.init_process()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
web_1  |     self.load_wsgi()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
web_1  |     self.wsgi = self.app.wsgi()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
web_1  |     self.callable = self.load()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
web_1  |     return self.load_wsgiapp()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
web_1  |     return util.import_app(self.app_uri)
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
web_1  |     __import__(module)
web_1  |   File "/app/liberapay/main.py", line 21, in <module>
web_1  |     from liberapay import utils, wireup
web_1  |   File "/app/liberapay/wireup.py", line 34, in <module>
web_1  |     import liberapay.billing.payday
web_1  |   File "/app/liberapay/billing/payday.py", line 21, in <module>
web_1  |     from liberapay.billing.transactions import Money, transfer
web_1  |   File "/app/liberapay/billing/transactions.py", line 25, in <module>
web_1  |     from liberapay.models.participant import Participant
web_1  |   File "/app/liberapay/models/participant.py", line 71, in <module>
web_1  |     from liberapay.utils import (
web_1  |   File "/app/liberapay/utils/emails.py", line 5, in <module>
web_1  |     from dns.exception import DNSException
web_1  | ImportError: No module named dns.exception
web_1  | [2018-09-13 13:24:05 +0000] [13] [ERROR] Exception in worker process
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
web_1  |     worker.init_process()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 126, in init_process
web_1  |     self.load_wsgi()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
web_1  |     self.wsgi = self.app.wsgi()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
web_1  |     self.callable = self.load()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
web_1  |     return self.load_wsgiapp()
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
web_1  |     return util.import_app(self.app_uri)
web_1  |   File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 357, in import_app
web_1  |     __import__(module)
web_1  |   File "/app/liberapay/main.py", line 21, in <module>
web_1  |     from liberapay import utils, wireup
web_1  |   File "/app/liberapay/wireup.py", line 34, in <module>
web_1  |     import liberapay.billing.payday
web_1  |   File "/app/liberapay/billing/payday.py", line 21, in <module>
web_1  |     from liberapay.billing.transactions import Money, transfer
web_1  |   File "/app/liberapay/billing/transactions.py", line 25, in <module>
web_1  |     from liberapay.models.participant import Participant
web_1  |   File "/app/liberapay/models/participant.py", line 71, in <module>
web_1  |     from liberapay.utils import (
web_1  |   File "/app/liberapay/utils/emails.py", line 5, in <module>
web_1  |     from dns.exception import DNSException
web_1  | ImportError: No module named dns.exception
web_1  | [2018-09-13 13:24:05 +0000] [15] [INFO] Worker exiting (pid: 15)
web_1  | [2018-09-13 13:24:05 +0000] [13] [INFO] Worker exiting (pid: 13)
web_1  | [2018-09-13 13:24:35 +0000] [9] [INFO] Shutting down: Master
web_1  | [2018-09-13 13:24:35 +0000] [9] [INFO] Reason: Worker failed to boot.
```

It looks like I have a dependency problem. Any idea to fix that?

**Comment by mattbk** [comment]
Yeah, you need to install that module. This was added in https://github.com/liberapay/liberapay.com/commit/bd830c95486591e85c9a7075560ecd8ba2d5d5df#diff-ba951dcdfc393700974a4eb3449bdb50.

**Comment by MartinDelille** [comment]
How?

**Comment by mattbk** [comment]
Did you rebuild the Docker container since that commit? 

> # build the local container
> docker-compose build

I would guess that is where the dependencies are installed.
