### ISSUE TITLE
make schema error

### ISSUE THREAD

**Issue by MartinDelille** [liberapay/liberapay.com#127]
I tried to set up the local environment and I didn't manage to finish the database setup. When typing `make schema`, I have the following outpu:

    env/bin/honcho run -e defaults.env,local.env ./recreate-schema.sh
    make: env/bin/honcho: No such file or directory
    make: *** [schema] Error 1

Sorry if it's trivial I'm kind of new to python and postgresql.

**Comment by MartinDelille** [comment]
(the file *env/bin/honcho* is present and has the executable flag)

**Comment by MartinDelille** [comment]
My mistake this is just that I moved the repo folder after configuring the environment. Running `make clean` and starting over fixed the problem!

**Comment by Skybladev2** [comment]
Hi @MartinDelille 
I have exactly the same error, but can not fix it.

I installed honcho like described in [the docs](https://media.readthedocs.org/pdf/honcho/latest/honcho.pdf):
```
pip install honcho
```

This puts honcho to my `/usr/local/lib/python2.7/dist-packages/` folder. However, don't see any executables there:
```
skyblade@ubuntu:/usr/local/lib/python2.7/dist-packages/honcho$ ls
colour.py   command.pyc  environ.py   __init__.py   manager.pyc  process.py
colour.pyc  compat.py    environ.pyc  __init__.pyc  printer.py   process.pyc
command.py  compat.pyc   export       manager.py    printer.pyc
```

Do you happen to know what I'm doing wrong?

**Comment by Changaco** [comment]
@Skybladev2 Have you tried `make clean env schema`? Can you copy-paste the output of that command?

**Comment by Skybladev2** [comment]
@Changaco No. When i tried it, new error occured.
I'll show complete log:

```
skyblade@ubuntu:~/Desktop$ ls
skyblade@ubuntu:~/Desktop$ virtualenv --python=/usr/bin/python2.7 liberapay
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /home/skyblade/Desktop/liberapay/bin/python2.7
Also creating executable in /home/skyblade/Desktop/liberapay/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
skyblade@ubuntu:~/Desktop$ cd liberapay/
skyblade@ubuntu:~/Desktop/liberapay$ git clone https://github.com/Skybladev2/liberapay.com.git
Cloning into 'liberapay.com'...
remote: Counting objects: 61014, done.
remote: Compressing objects: 100% (185/185), done.
remote: Total 61014 (delta 191), reused 239 (delta 134), pack-reused 60688
Receiving objects: 100% (61014/61014), 28.19 MiB | 443.00 KiB/s, done.
Resolving deltas: 100% (41197/41197), done.
skyblade@ubuntu:~/Desktop/liberapay$ ls
bin  lib  liberapay.com  local  share
skyblade@ubuntu:~/Desktop/liberapay$ cd liberapay.com/
skyblade@ubuntu:~/Desktop/liberapay/liberapay.com$ make clean env schema
rm -rf env *.egg *.egg-info
find . -name \*.pyc -delete
"/usr/bin/python2.7" -m ensurepip --user || make --no-print-directory _warning
ensurepip is disabled in Debian/Ubuntu for the system python.

Python modules For the system python are usually handled by dpkg and apt-get.

    apt-get install python-<module name>

Install the python-pip package to use pip itself.  Using pip together
with the system python might have unexpected results for any system installed
module, so use it on your own risk, or make sure to only use it in virtual
environments.

-e 
Warning: you're using an old version of python, you really should upgrade!

"/usr/bin/python2.7" -m pip --disable-pip-version-check install --user "virtualenv>=15.0.0"
Requirement already satisfied: virtualenv>=15.0.0 in /home/skyblade/.local/lib/python2.7/site-packages
"/usr/bin/python2.7" -m virtualenv --no-download ./env/
New python executable in /home/skyblade/Desktop/liberapay/liberapay.com/env/bin/python2.7
Also creating executable in /home/skyblade/Desktop/liberapay/liberapay.com/env/bin/python
Installing setuptools, pip, wheel...done.
env/bin/pip --disable-pip-version-check install --require-hashes $(for f in requirements_*.txt; do echo "-r $f"; done)
Collecting python-mimeparse==1.6.0 (from -r requirements_base.txt (line 1))
  Using cached python_mimeparse-1.6.0-py2.py3-none-any.whl
Collecting first==2.0.1 (from -r requirements_base.txt (line 4))
  Using cached first-2.0.1-py2.py3-none-any.whl
Collecting dependency_injection==1.1.0 (from -r requirements_base.txt (line 7))
  Using cached dependency_injection-1.1.0.tar.gz
Collecting algorithm==1.2.0 (from -r requirements_base.txt (line 9))
  Using cached algorithm-1.2.0.tar.gz
Collecting filesystem_tree==1.1.2 (from -r requirements_base.txt (line 12))
  Using cached filesystem_tree-1.1.2.tar.gz
Collecting aspen==1.0rc1 (from -r requirements_base.txt (line 14))
  Using cached aspen-1.0rc1.zip
Collecting pando==0.44 (from -r requirements_base.txt (line 19))
  Using cached pando-0.44-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r requirements_base.txt (line 25))
  Using cached MarkupSafe-0.23.tar.gz
Collecting Jinja2==2.8 (from -r requirements_base.txt (line 27))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting aspen-jinja2==0.5 (from -r requirements_base.txt (line 30))
  Using cached aspen_jinja2-0.5-py2.py3-none-any.whl
Collecting psycopg2==2.6.1 (from -r requirements_base.txt (line 34))
  Using cached psycopg2-2.6.1.tar.gz
Collecting postgres==2.2.1 (from -r requirements_base.txt (line 38))
  Using cached postgres-2.2.1.tar.gz
Collecting simplejson==3.8.1 (from -r requirements_base.txt (line 41))
  Using cached simplejson-3.8.1.tar.gz
Collecting certifi==0.0.8 (from -r requirements_base.txt (line 44))
  Using cached certifi-0.0.8.tar.gz
Collecting pyasn1==0.1.3 (from -r requirements_base.txt (line 46))
  Using cached pyasn1-0.1.3.tar.gz
Collecting chardet==1.0.1 (from -r requirements_base.txt (line 49))
  Using cached chardet-1.0.1.tar.gz
Collecting oauthlib==1.0.3 (from -r requirements_base.txt (line 51))
  Using cached oauthlib-1.0.3.tar.gz
Collecting requests==2.6.0 (from -r requirements_base.txt (line 53))
  Using cached requests-2.6.0-py2.py3-none-any.whl
Collecting requests-oauthlib==0.6.1 (from -r requirements_base.txt (line 56))
  Using cached requests_oauthlib-0.6.1-py2.py3-none-any.whl
Collecting xmltodict==0.8.4 (from -r requirements_base.txt (line 59))
  Using cached xmltodict-0.8.4.tar.gz
Collecting blinker==1.4 (from -r requirements_base.txt (line 62))
  Using cached blinker-1.4.tar.gz
Collecting mangopaysdk==3.0.6 (from -r requirements_base.txt (line 64))
  Using cached mangopaysdk-3.0.6.tar.gz
Collecting contextlib2==0.4.0 (from -r requirements_base.txt (line 67))
  Using cached contextlib2-0.4.0.tar.gz
Collecting raven==5.25.0 (from -r requirements_base.txt (line 69))
  Using cached raven-5.25.0-py2.py3-none-any.whl
Collecting six==1.8.0 (from -r requirements_base.txt (line 73))
  Using cached six-1.8.0-py2.py3-none-any.whl
Collecting libsass==0.11.1 (from -r requirements_base.txt (line 76))
  Using cached libsass-0.11.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting environment==1.0.0 (from -r requirements_base.txt (line 83))
  Using cached environment-1.0.0.tar.gz
Collecting html2text==2016.4.2 (from -r requirements_base.txt (line 86))
  Using cached html2text-2016.4.2.tar.gz
Collecting MailShake==0.12.1 (from -r requirements_base.txt (line 88))
  Using cached MailShake-0.12.1.tar.gz
Collecting pytz==2015.7 (from -r requirements_base.txt (line 91))
  Using cached pytz-2015.7-py2.py3-none-any.whl
Collecting Babel==2.3.4 (from -r requirements_base.txt (line 97))
  Using cached Babel-2.3.4-py2.py3-none-any.whl
Collecting misaka==2.0.0 (from -r requirements_base.txt (line 101))
  Using cached misaka-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-BXivs5/misaka/setup.py", line 68, in <module>
        cffi_modules=['build_ffi.py:ffi'],
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/skyblade/Desktop/liberapay/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/skyblade/Desktop/liberapay/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/skyblade/Desktop/liberapay/liberapay.com/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/skyblade/Desktop/liberapay/liberapay.com/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/home/skyblade/Desktop/liberapay/liberapay.com/env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/home/skyblade/Desktop/liberapay/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/skyblade/Desktop/liberapay/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/skyblade/Desktop/liberapay/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/skyblade/Desktop/liberapay/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/skyblade/Desktop/liberapay/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/skyblade/Desktop/liberapay/liberapay.com/env/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1103, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BXivs5/misaka/
Makefile:22: recipe for target 'env' failed
make: *** [env] Error 1
```

**Comment by Changaco** [comment]
Looks like you're missing Python's C headers. `apt-get install python-dev` should fix that.

**Comment by Skybladev2** [comment]
@Changaco Success!
I faced another missed packages after that, but google helped me to resolve them :)
Now I have the site up and running.
