### ISSUE TITLE
Web server doesn't react well to DB restart

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#1451]
About 6 hours ago the database was restarted for the first time for an automated upgrade. Liberapay used to have problems with DB crashes when it was hosted on OpenShift so it has mechanisms to avoid failing completely and to recover automatically, but those mechanisms aren't working properly anymore. One big problem is that Liberapay is designed to run with Gunicorn, but it's currently running under Apache's mod_wsgi instead in production.

**Comment by Changaco** [comment]
The server was unable to recover because Apache expects the WSGI script to be "reentrant" (as in "executable more than once in the same process"), but ours isn't:

```
[Tue Feb 19 03:52:44.735580 2019] [:error] [pid 5384] /opt/python/run/venv/local/lib/python3.6/site-packages/aspen/renderers.py:8: FutureWarning: aspen.renderers is deprecated and will be removed in a future version. Please use aspen.simplates.renderers instead.
[Tue Feb 19 03:52:44.735605 2019] [:error] [pid 5384] 'Please use aspen.simplates.renderers instead.', FutureWarning)
[Tue Feb 19 03:52:45.009172 2019] [:error] [pid 5384] INFO:botocore.credentials:Found credentials in environment variables.
[Tue Feb 19 03:52:45.193793 2019] [:error] [pid 5384] [remote 172.31.40.66:60] mod_wsgi (pid=5384): Target WSGI script '/opt/python/current/app/liberapay/main.py' cannot be loaded as Python module.
[Tue Feb 19 03:52:45.193852 2019] [:error] [pid 5384] [remote 172.31.40.66:60] mod_wsgi (pid=5384): Exception occurred processing WSGI script '/opt/python/current/app/liberapay/main.py'.
[Tue Feb 19 03:52:45.204410 2019] [:error] [pid 5384] [remote 172.31.40.66:60] Traceback (most recent call last):
[Tue Feb 19 03:52:45.204452 2019] [:error] [pid 5384] [remote 172.31.40.66:60] File "/opt/python/current/app/liberapay/main.py", line 95, in <module>
[Tue Feb 19 03:52:45.204457 2019] [:error] [pid 5384] [remote 172.31.40.66:60] d = wireup.full_algorithm.run(**website.__dict__)
[Tue Feb 19 03:52:45.204463 2019] [:error] [pid 5384] [remote 172.31.40.66:60] File "/opt/python/run/venv/local/lib/python3.6/site-packages/algorithm.py", line 342, in run
[Tue Feb 19 03:52:45.204465 2019] [:error] [pid 5384] [remote 172.31.40.66:60] loop(False)
[Tue Feb 19 03:52:45.204470 2019] [:error] [pid 5384] [remote 172.31.40.66:60] File "/opt/python/run/venv/local/lib/python3.6/site-packages/algorithm.py", line 333, in loop
[Tue Feb 19 03:52:45.204472 2019] [:error] [pid 5384] [remote 172.31.40.66:60] loop(True)
[Tue Feb 19 03:52:45.204477 2019] [:error] [pid 5384] [remote 172.31.40.66:60] File "/opt/python/run/venv/local/lib/python3.6/site-packages/algorithm.py", line 321, in loop
[Tue Feb 19 03:52:45.204479 2019] [:error] [pid 5384] [remote 172.31.40.66:60] new_state = function(**deps.as_kwargs)
[Tue Feb 19 03:52:45.204484 2019] [:error] [pid 5384] [remote 172.31.40.66:60] File "/opt/python/current/app/liberapay/wireup.py", line 156, in database
[Tue Feb 19 03:52:45.204486 2019] [:error] [pid 5384] [remote 172.31.40.66:60] oid = db.one("SELECT 'currency_amount'::regtype::oid")
[Tue Feb 19 03:52:45.204491 2019] [:error] [pid 5384] [remote 172.31.40.66:60] File "/opt/python/current/app/liberapay/wireup.py", line 113, in __getattr__
[Tue Feb 19 03:52:45.204493 2019] [:error] [pid 5384] [remote 172.31.40.66:60] raise NeedDatabase()
[Tue Feb 19 03:52:45.204508 2019] [:error] [pid 5384] [remote 172.31.40.66:60] liberapay.exceptions.NeedDatabase: 503 Service Unavailable:
[Tue Feb 19 03:52:45.208356 2019] [:error] [pid 5384] [remote 172.31.29.90:64] mod_wsgi (pid=5384): Target WSGI script '/opt/python/current/app/liberapay/main.py' cannot be loaded as Python module.
[Tue Feb 19 03:52:45.208386 2019] [:error] [pid 5384] [remote 172.31.29.90:64] mod_wsgi (pid=5384): Exception occurred processing WSGI script '/opt/python/current/app/liberapay/main.py'.
[Tue Feb 19 03:52:45.208447 2019] [:error] [pid 5384] [remote 172.31.29.90:64] Traceback (most recent call last):
[Tue Feb 19 03:52:45.208467 2019] [:error] [pid 5384] [remote 172.31.29.90:64] File "/opt/python/current/app/liberapay/main.py", line 88, in <module>
[Tue Feb 19 03:52:45.208471 2019] [:error] [pid 5384] [remote 172.31.29.90:64] del website.body_parsers[website.media_type_json]
[Tue Feb 19 03:52:45.208482 2019] [:error] [pid 5384] [remote 172.31.29.90:64] KeyError: 'application/json'
[Tue Feb 19 03:52:45.212270 2019] [:error] [pid 5384] [remote 172.31.29.90:52] mod_wsgi (pid=5384): Target WSGI script '/opt/python/current/app/liberapay/main.py' cannot be loaded as Python module.
[Tue Feb 19 03:52:45.212302 2019] [:error] [pid 5384] [remote 172.31.29.90:52] mod_wsgi (pid=5384): Exception occurred processing WSGI script '/opt/python/current/app/liberapay/main.py'.
[Tue Feb 19 03:52:45.212356 2019] [:error] [pid 5384] [remote 172.31.29.90:52] Traceback (most recent call last):
[Tue Feb 19 03:52:45.212377 2019] [:error] [pid 5384] [remote 172.31.29.90:52] File "/opt/python/current/app/liberapay/main.py", line 88, in <module>
[Tue Feb 19 03:52:45.212380 2019] [:error] [pid 5384] [remote 172.31.29.90:52] del website.body_parsers[website.media_type_json]
[Tue Feb 19 03:52:45.212392 2019] [:error] [pid 5384] [remote 172.31.29.90:52] KeyError: 'application/json'
```

This `KeyError` happened over and over again until I restarted the server with `sudo /usr/local/bin/supervisorctl -c /opt/python/etc/supervisord.conf restart httpd`.

**Comment by Changaco** [comment]
Clearing Python's module cache could help make the script "reentrant": http://code.activestate.com/recipes/81731-reloading-all-modules/
