### ISSUE TITLE
Transient psycopg errors result in 500s

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#234]
https://sentry.changaco.oy.lc/share/issue/322e3430/ and https://sentry.changaco.oy.lc/share/issue/322e3431/

**Comment by Changaco** [comment]
Looks like the root cause could be hardware (RAM) defect: http://www.postgresql.org/message-id/17043.1100793419@sss.pgh.pa.us

**Comment by Changaco** [comment]
Closing. I'll reopen if we hit this problem again in the future.

**Comment by Changaco** [comment]
Actually, I got one when I rebooted the DB on AWS:

```
FormattingError: Traceback (most recent call last):
  File "/opt/python/current/app/liberapay/utils/query_cache.py", line 171, in _do_query
    entry.result = fetchfunc(query, params)
  File "/opt/python/run/venv/lib/python2.7/site-packages/postgres/__init__.py", line 548, in all
    return cursor.all(sql, parameters)
  File "/opt/python/run/venv/lib/python2.7/site-packages/postgres/context_managers.py", line 46, in __exit__
    self.conn.rollback()
InterfaceError: connection already closed

  File "site-packages/algorithm.py", line 321, in loop
    new_state = function(**deps.as_kwargs)
  File "aspen/request_processor/algorithm.py", line 73, in render_resource
    return {'output': resource.render(state)}
  File "aspen/http/resource.py", line 78, in render
    return super(Dynamic, self).render(available[0], state)
  File "aspen/simplates/simplate.py", line 121, in render
    exec(self.pages[1], context)
  File "/opt/python/bundle/13/app/www/index.html.spt", line 18, in <module>
    """)
  File "liberapay/utils/query_cache.py", line 99, in all
    return self._do_query(self.db.all, query, params, process)
  File "liberapay/utils/query_cache.py", line 191, in _do_query
    raise entry.exc[0]
```

https://sentry.io/share/issue/3132343535362e323336363038353239/

**Comment by Changaco** [comment]
I think this is fixed now.
