### ISSUE TITLE
Investigate failing sign in tests.

### ISSUE THREAD

**Issue by aandis** [liberapay/liberapay.com#264]
Some sign in tests are failing. All seem to have the same error. I am also not able to sign in locally. I am guessing this has something to do with that.

**Comment by aandis** [comment]
Here's an example of one that's failing.

`TestSignIn.test_log_in`


```bash

self = <test_sign_in.TestSignIn testMethod=test_log_in>

    def test_log_in(self):
        password = 'password'
        alice = self.make_participant('alice')
        alice.update_password(password)
>       self.log_in_and_check(alice, password)

tests/py/test_sign_in.py:57: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/py/test_sign_in.py:45: in log_in_and_check
    self.check_with_about_me(p.username, r.headers.cookie)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_sign_in.TestSignIn testMethod=test_log_in>, username = 'alice'
cookies = <SimpleCookie: csrf_token='ThisIsATokenThatIsThirtyTwoBytes' session='1:7ede36d936b74178b80cfdc136da52da'>

    def check_with_about_me(self, username, cookies):
        r = self.client.GET('/about/me/', cookies=cookies, raise_immediately=False)
>       assert r.code == 302
E       AssertionError: assert 500 == 302
E        +  where 500 = <Response: 500 Internal Server Error>.code

tests/py/test_sign_in.py:50: AssertionError
---------------------------------------------------------------- Captured stderr call -----------------------------------------------------------------
Traceback (most recent call last):
  File "liberapay.com/env/lib/python2.7/site-packages/algorithm.py", line 288, in run
    new_state = function(**deps.as_kwargs)
  File "liberapay.com/liberapay/security/authentication.py", line 121, in authenticate_user_if_possible
    p = Participant.authenticate('id', 'session', *creds)
  File "liberapay.com/liberapay/models/participant.py", line 174, in authenticate
    p = cls._from_thing(k1, v1)
  File "liberapay.com/liberapay/models/participant.py", line 164, in _from_thing
    """.format(thing), (value,))
  File "liberapay.com/env/lib/python2.7/site-packages/postgres/__init__.py", line 482, in one
    return cursor.one(sql, parameters, default)
  File "liberapay.com/env/lib/python2.7/site-packages/postgres/cursors.py", line 105, in one
    out = self._some(sql, parameters, lo=0, hi=1)
  File "liberapay.com/env/lib/python2.7/site-packages/postgres/cursors.py", line 127, in _some
    self.execute(sql, parameters)
  File "liberapay.com/env/lib/python2.7/site-packages/psycopg2/extras.py", line 288, in execute
    return super(NamedTupleCursor, self).execute(query, vars)
DataError: invalid input syntax for integer: "Set-Cookie"
LINE 4:              WHERE id='Set-Cookie'

```

**Comment by Changaco** [comment]
It looks like aspen's testing client uses the standard `Cookie` module in a way that isn't supported by the version of python you're using (2.7.8 , right?).

**Comment by Changaco** [comment]
Specifically, this line from ` grep -nri cookie env/lib/python2.7/site-packages/aspen/`:

    env/lib/python2.7/site-packages/aspen/testing/client.py:134:                self.cookie.update(response.headers.cookie)

Here `self.cookie` is a `SimpleCookie`, and the `__setitem__` method of that class was modified between [v2.7.8](https://hg.python.org/cpython/file/v2.7.8/Lib/Cookie.py) and [v2.7.9](https://hg.python.org/cpython/file/v2.7.8/Lib/Cookie.py).
