### ISSUE TITLE
Weird things are happening with HTTP status codes

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#362]
```
[2016-06-22 06:35:47 +0000] [32579] [ERROR] Error handling request /sign-in?back_to=/about/
Traceback (most recent call last):
  File "/var/lib/openshift/56b0dd352d52714c5d0001dc/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/var/lib/openshift/56b0dd352d52714c5d0001dc/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/var/lib/openshift/56b0dd352d52714c5d0001dc/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/aspen/website.py", line 40, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/lib/openshift/56b0dd352d52714c5d0001dc/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/aspen/website.py", line 53, in wsgi_app
    return wsgi(environ, start_response)
  File "/var/lib/openshift/56b0dd352d52714c5d0001dc/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/aspen/http/response.py", line 109, in __call__
    start_response(wsgi_status, wsgi_headers)
  File "/var/lib/openshift/56b0dd352d52714c5d0001dc/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 253, in start_response
    self.status_code = int(self.status.split()[0])
IndexError: list index out of range
[22/Jun/2016:06:36:53 -0400] 500 0.000932s liberapay.com "POST /sign-in?back_to=/about/ HTTP/1.1" - "-"
```

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.mangopay.com
[22/Jun/2016:06:45:57 -0400] 406 0.534756s liberapay.com "GET /callbacks/mangopay?RessourceId=58097621&EventType=PAYIN_NORMAL_SUCCEEDED&Date=1466592355 HTTP/1.1" 152 "-"
```

```
[21/Jun/2016:17:13:28 -0400] raymond 0.130400s liberapay.com "POST /~xxxx/tip HTTP/1.1" 9103 "https://liberapay.com/~xxxx/tip"
```

**Comment by Changaco** [comment]
And another:

```
[2016-06-22 07:23:26 +0000] [40674] [ERROR] Error handling request /sign-in?back_to=/about/
Traceback (most recent call last):
  File "/var/lib/openshift/56b0dd352d52714c5d0001dc/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/var/lib/openshift/56b0dd352d52714c5d0001dc/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 171, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/var/lib/openshift/56b0dd352d52714c5d0001dc/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/aspen/website.py", line 40, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/lib/openshift/56b0dd352d52714c5d0001dc/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/aspen/website.py", line 53, in wsgi_app
    return wsgi(environ, start_response)
  File "/var/lib/openshift/56b0dd352d52714c5d0001dc/app-root/runtime/dependencies/python/virtenv/lib/python2.7/site-packages/aspen/http/response.py", line 91, in __call__
    wsgi_status = str(self)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xc9' in position 6: ordinal not in range(128)
[22/Jun/2016:07:23:26 -0400] 500 0.001777s fr.liberapay.com "POST /sign-in?back_to=/about/ HTTP/1.1" - "-"
```
