### ISSUE TITLE
Downtime

### ISSUE THREAD

**Issue by Changaco** [liberapay/liberapay.com#760]
liberapay.com has failed for 5 hours today between 03:01 and 07:59 UTC.

The error from PostgreSQL is: `FATAL:  remaining connection slots are reserved for non-replication superuser connections`.

It looks like something went wrong during the weekly "Managed Update" of the app server.

In the postgres logs I'm also seeing:

- many `LOG: could not receive data from client: Connection reset by peer` during the outage
- some `FATAL: terminating connection due to idle-in-transaction timeout` during recovery
- exactly 20 `FATAL: terminating connection due to administrator command` when I triggered a DB reboot

**Comment by Changaco** [comment]
In the RDS config `max_connections` is set to `LEAST({DBInstanceClassMemory/9531392},5000)`, so with 506 MB of memory shouldn't the result be 53?

In the app env `DATABASE_MAXCONN` is `100`.

**Comment by Changaco** [comment]
A secondary issue is that what I saw during the outage was a standard Apache 500 error page instead of Liberapay's error page.

**Comment by Changaco** [comment]
Other relevant postgres settings:

![screenshot_20171024_111807](https://user-images.githubusercontent.com/1581590/31934658-03c5c89c-b8ad-11e7-83be-133af5071956.png)

**Comment by Changaco** [comment]
AFAICT if the root cause was a bug in the app leading to a deadlock then there shouldn't have been a general outage, only a few timeouts.

**Comment by Changaco** [comment]
FTR, the traceback from Sentry:

```
OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections

  File "liberapay/wireup.py", line 81, in database
    db = DB(dburl, maxconn=maxconn)
  File "postgres/__init__.py", line 338, in __init__
    , connection_factory=Connection
  File "psycopg2/pool.py", line 161, in __init__
    self, minconn, maxconn, *args, **kwargs)
  File "psycopg2/pool.py", line 58, in __init__
    self._connect()
  File "psycopg2/pool.py", line 62, in _connect
    conn = psycopg2.connect(*self._args, **self._kwargs)
  File "psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
  File "postgres/__init__.py", line 773, in __init__
    psycopg2.extensions.connection.__init__(self, *a, **kw)
```

**Comment by Changaco** [comment]
What would happen if we set `DATABASE_MAXCONN` too low? Apparently we would get exceptions like this:

```
Traceback (most recent call last):
  File "liberapay/cron.py", line 51, in f
    func()
  File "liberapay/models/participant.py", line 812, in dequeue_emails
    with cls.db.get_cursor() as cursor:
  File "env/lib/python2.7/site-packages/postgres/context_managers.py", line 35, in __enter__
    self.conn = self.pool.getconn()
  File "env/lib/python2.7/site-packages/psycopg2/pool.py", line 168, in getconn
    return self._getconn(key)
  File "env/lib/python2.7/site-packages/psycopg2/pool.py", line 91, in _getconn
    raise PoolError("connection pool exhausted")
PoolError: connection pool exhausted
```

**Comment by Changaco** [comment]
Found the secondary issue in Apache's error log:

```
mod_wsgi (pid=6502): Target WSGI script '/opt/python/current/app/liberapay/main.py' cannot be loaded as Python module.
mod_wsgi (pid=6502): Exception occurred processing WSGI script '/opt/python/current/app/liberapay/main.py'.
Traceback (most recent call last):
File "/opt/python/current/app/liberapay/main.py", line 73, in <module>
website.__dict__.update(wireup.full_algorithm.run(**website.__dict__))
File "/opt/python/run/venv/lib/python2.7/site-packages/algorithm.py", line 342, in run
loop(False)
File "/opt/python/run/venv/lib/python2.7/site-packages/algorithm.py", line 333, in loop
loop(True)
File "/opt/python/run/venv/lib/python2.7/site-packages/algorithm.py", line 321, in loop
new_state = function(**deps.as_kwargs)
File "/opt/python/current/app/liberapay/wireup.py", line 235, in trusted_proxies
for networks in (app_conf.trusted_proxies or ())
File "/opt/python/current/app/liberapay/wireup.py", line 234, in <genexpr>
sum((parse_network(net) for net in networks), [])
File "/opt/python/current/app/liberapay/wireup.py", line 228, in parse_network
urlretrieve(net, filename)
File "/usr/lib64/python2.7/urllib.py", line 98, in urlretrieve
return opener.retrieve(url, filename, reporthook, data)
File "/usr/lib64/python2.7/urllib.py", line 249, in retrieve
tfp = open(filename, 'wb')
IOError: [Errno 13] Permission denied: u'/home/wsgi/trusted_proxies/https%3A%2F%2Fwww.cloudflare.com%2Fips-v4'
```

**Comment by Changaco** [comment]
The access log shows that the "Managed Update" was in fact successful since the new instance correctly answered some requests, but for some reason it was considered a failure and rolled back. That's when the secondary issue appeared.

**Comment by Changaco** [comment]
```
[ec2-user@... ~]$ ls -l /home/wsgi/
total 112
-rw-r--r-- 1 wsgi wsgi 104882 Oct 18 11:26 payday-89.txt
-rw-r--r-- 1 wsgi wsgi      4 Oct 18 11:22 payday.pid
drwxr-xr-x 2 root root   4096 Oct 17 02:48 trusted_proxies
[ec2-user@... ~]$ ls -l /home/wsgi/trusted_proxies/
total 8
-rw-r--r-- 1 root root 217 Oct 24 07:58 https%3A%2F%2Fwww.cloudflare.com%2Fips-v4
-rw-r--r-- 1 root root 105 Oct 24 07:58 https%3A%2F%2Fwww.cloudflare.com%2Fips-v6
```

**Comment by Changaco** [comment]
```sql
> show max_connections;
 max_connections 
-----------------
 87
(1 row)
```

**Comment by Changaco** [comment]
So…

- [ ] lower `DATABASE_MAXCONN` from `100` to `30`
- [ ] handle `PoolError` exceptions properly
- [ ] fix the ownership of `/home/wsgi/trusted_proxies`
- [ ] catch exceptions in `trusted_proxies()` and send them to Sentry
- [ ] set up proper [Sentry Alert Rules](https://blog.sentry.io/2017/10/12/proactive-alert-rules)
- [ ] make sure the signals intended for gunicorn don't mess up apache

**Comment by Changaco** [comment]
This made us miss a callback from mangopay, resulting in a bankwire payin not being completed.

I'm going to finally take care of #519 to detect this kind of problem.

**Comment by Changaco** [comment]
Reticketed the remaining items. Closing.
